Recuperando dadosapi
paulotelles/github_app pull request #7
Opened 2021-02-08 19:55 UTC by paulotelles

Criação dos js para construção da pagina repositories.hhtml através da comunicação da API do github

2021-02-08 21:09 UTC, vncsrbro requested changes

2021-02-08 21:09 UTC, vncsrbro commented on src/js/pages/api.js
> +function apiRequest(urlOrigin) {
Se eu tento entrar direto na página `http://localhost:3000/repositories.html` ele me retorna o perfil `github.com/null`. Aparentemente essa função está sendo executada sem um parâmetro e atribuindo `null` no lugar do usuário.

2021-02-09 14:44 UTC, paulotelles commented on src/js/pages/card.js
> +    Object.keys(element).forEach((key) => {
corrigido

2021-02-09 14:45 UTC, paulotelles commented on src/sass/components/_card.scss
>      overflow: hidden;
corrigido

2021-02-10 13:28 UTC, vncsrbro requested changes

2021-02-10 13:28 UTC, vncsrbro commented on src/js/modules/card.js
> +    // Object.keys(element).forEach((key) => {
Podemos remover os blocos de códigos comentados que não estão sendo utilizados.

2021-02-10 13:28 UTC, vncsrbro commented on src/js/modules/sidebar.js
> +  // Object.keys(model).forEach((key) => {
Podemos remover os blocos de códigos comentados que não estão sendo utilizados.

2021-02-10 13:28 UTC, vncsrbro commented on src/js/modules/api.js
> +/*module.exports.apiRequest = (urlOrigin) => {
Podemos remover os blocos de códigos comentados que não estão sendo utilizados.

2021-02-10 13:57 UTC, paulotelles commented on src/js/pages/sidebar.js
> +      model[key] = " ";
corrigido

2021-02-10 13:57 UTC, paulotelles commented on src/sass/pages/repositories.scss
> +  width: 100%;
corrigido

2021-02-10 13:59 UTC, paulotelles commented on src/js/pages/api.js
> +function apiRequest(urlOrigin) {
fiz uma regra para não acontecer mais esse problema em dois lugares, o primeiro que verifica se foi passado o usuário na url, e depois outro na api.js que agora pede a url de erro para retornar o usuário para consulta caso o usuário seja inválido.

2021-02-10 14:10 UTC, paulotelles commented on src/sass/components/_card.scss
> +    height: 72px;
corrigido

2021-02-10 14:10 UTC, paulotelles commented on src/js/modules/api.js
> +/*module.exports.apiRequest = (urlOrigin) => {
feito

2021-02-10 14:12 UTC, paulotelles commented on src/js/modules/sidebar.js
> +  // Object.keys(model).forEach((key) => {
feito

2021-02-10 14:35 UTC, vncsrbro requested changes

2021-02-10 14:35 UTC, vncsrbro commented on src/js/modules/card.js
> +    // Object.keys(element).forEach((key) => {
Faltou remover esse bloco comentado aqui.

2021-02-10 14:35 UTC, vncsrbro commented on src/js/pages/repositories.js
>  console.log(userName);
É preferível removermos as declarações de console.log quando já tivermos o código final e que não esta mais sendo debugado.

2021-02-10 14:41 UTC, vncsrbro commented on repositories.html
> +    <script src="./dist/js/card.js"></script>
Não estamos mais utilizando essas 3 chamadas de scripts.

2021-02-10 17:53 UTC, paulotelles commented on src/js/pages/repositories.js
>  console.log(userName);
feito.

2021-02-10 17:53 UTC, paulotelles commented on repositories.html
> +    <script src="./dist/js/card.js"></script>
removido

2021-02-10 18:02 UTC, vncsrbro approved these changes

2021-02-10 18:03 UTC, merged